---
- name: Install pyenv
  become: true
  become_user: "{{ USER }}"
  shell: curl https://pyenv.run | bash
  args:
    creates: "/home/{{ USER }}/.pyenv"

- name: Add path etc to .bashrc for pyenv
  lineinfile:
    dest: "/home/{{ USER }}/.bashrc"
    state: present
    create: true
    line: "{{ item }}"
  with_items:
    - 'export PYENV_ROOT="$HOME/.pyenv"'
    - 'export PATH="$PYENV_ROOT/bin:$PATH"'
    - 'eval "$(pyenv init -)"'
    - 'eval "$(pyenv virtualenv-init -)"'

- name: Ensure .pyenv permissions are set properly
  file:
    path: /home/{{ USER }}/.pyenv
    recurse: yes
    owner: "{{ USER }}"
    group: "{{ USER }}"
    state: directory

- name: Install default python version
  become: true
  become_user: "{{ USER }}"
  shell: . /home/{{ USER }}/.bashrc && /home/'{{ USER }}'/.pyenv/bin/pyenv install '{{ PYTHON_VERSION }}'
  args:
    creates: "/home/{{ USER }}/.pyenv/versions/{{ PYTHON_VERSION }}"

- name: Switch to new global python version
  become_user: "{{ USER }}"
  shell: /home/{{ USER }}/.pyenv/bin/pyenv global '{{ PYTHON_VERSION }}'
